### ISSUE TITLE
Xamarin developers have maximized resource sharing in their apps

### ISSUE THREAD

**Issue by maddymontaquila** [dotnet/xamarin#23]
- [x] o	Manage shared images, fonts, and other resources in a single .NET 6 project M P0
- [x] o	Declare app manifest values and permissions in a single .NET 6 project S P1
- [x] o	Application Icons are generated for all target platforms from a single .NET 6 project source M P0
- [x] o	Splash screens are generated for all target platforms from a single .NET 6 project source S P1
- [x] o	Splash screens can be written in XAML and shared XL P2
- [x] o	Shared assets are localizable L P2

**Comment by Aguilex** [comment]
Xamarin Tools comments ... initially, this is conceived as being focused on the SDKs, but there will be some impact in the IDEs once the mechanisms are ready that allows for sharing these resources. May need a new Assets Manager and App Manifest editor in VS and VSMac.
