### ISSUE TITLE
Hey sorry, I was busy running behind a release and deployment the past week.

### ISSUE THREAD

**Issue by pasha-o** [dotnet/xamarin#41]
Hey sorry, I was busy running behind a release and deployment the past week.

Here's a summary:

- [ ] Yeah, I only prefer using a real device to test my apps. And it's USB debugging latched to my PC with a cable, not wireless ADB.
- [ ] The device I used was Samsung Galaxy S22.
- [ ] Normal debugging breakpoints hit easily. No issues at all. XAML won't update
- [ ] Works fine with Windows, Fails sometimes random with Android real device
- [ ] Tried other devices other than my Galaxy S22, Same issue randomly. I believe it's originating from VS, not the smartphone
- [ ] This is mostly prominent when building after updating Visual Studio MAUI workload for first time

_Originally posted by @sangeethnandakumar in https://github.com/dotnet/maui/issues/16267#issuecomment-1666448073_

**Comment by akoeplinger** [comment]
Please use the relevant issues in the dotnet/maui repo.
