### ISSUE TITLE
I also tested this on the same version of Visual Studio you're running, with what I believe to be the same workloads, and it works correctly on my Pixel 6 and Pixel 4a running Android 13. Maybe this is specific to your device (or device type)? How are you debugging your application? Wireless? directly connected to your PC?

### ISSUE THREAD

**Issue by pasha-o** [dotnet/xamarin#42]
I also tested this on the same version of Visual Studio you're running, with what I believe to be the same workloads, and it works correctly on my Pixel 6 and Pixel 4a running Android 13. Maybe this is specific to your device (or device type)? How are you debugging your application? Wireless? directly connected to your PC?

_Originally posted by @drasticactions in https://github.com/dotnet/maui/issues/16267#issuecomment-1647806946_

**Comment by pasha-o** [comment]
hi I wanted to keep this issue open as the latest visual studio update broke Xamarin.forms hot reload. I believe the same issue is also reported for MAUI

**Comment by akoeplinger** [comment]
Please use the relevant issues in the dotnet/maui repo.
