### ISSUE TITLE
Android app crashes while selecting other options instead of "Allow all the time" in location permission popup

### ISSUE THREAD

**Issue by SavitaPtl** [dotnet/xamarin#44]
On an android device, when requesting location permission, if the user selects "Allow only while using the app", "Ask every time", "Don't allow"  option on the popup the app crashes. It only works with "Allow all the time".

The android manifest is correctly configured with the following permissions:

<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />

**Steps to Reproduce**
Run a fresh install app, on an android device. Observe the popup that request for device location, select "while using the app" it will go to app setting-> location permission then select option like "Allow only while using the app", "Ask every time", "Don't allow"  on the popup the app crashes. It only works with "Allow all the time".

![Screenshot_1708945057](https://github.com/dotnet/xamarin/assets/148308146/5642b8a9-fcf4-470f-b206-73367c258027)

**Expected Behavior**
App should work with all the options

**Actual Behavior**
Isn't it. It only works with "Allow all the time".

**Here is sample project link**
https://github.com/jitendrajadav/XamarinForms.LocationService/tree/master

**Comment by akoeplinger** [comment]
Please open the issue in https://github.com/xamarin/xamarin-android, this repo was used for planning and is not monitored.
